// Historical election data — loaded from pre-built static JSON (public/historical-ward-data.json).
// That file is generated at build time by scripts/build-historical-data.mjs, which fetches
// directly from the Dane County API. Zero hardcoded values; all data is real API data.

import { RaceType } from './api';
import { addLog } from './debug-log';

export interface HistoricalRaceData {
    electionId: string;
    electionName: string;
    electionDate: string;
    raceId: string;
    raceName: string;
    raceType: RaceType;
    wardResults: Map<string, WardResult>; // key: normalized ward name
}

export interface WardResult {
    candidates: { name: string; votes: number }[];
    totalVotes: number;
    topCandidate: string;
    margin: number; // (1st - 2nd) / total
}

// In-memory cache for the session (1 hour TTL)
let historicalDataCache: Map<RaceType, HistoricalRaceData[]> | null = null;
let cacheTimestamp: number = 0;
const CACHE_DURATION = 1000 * 60 * 60; // 1 hour

/**
 * Load pre-built historical data from public/historical-ward-data.json.
 * This file is generated by `npm run build:historical` (or automatically via prebuild).
 * Falls back gracefully if the file is missing (e.g. first run before building).
 */
export async function fetchHistoricalData(): Promise<Map<RaceType, HistoricalRaceData[]>> {
    if (historicalDataCache && (Date.now() - cacheTimestamp) < CACHE_DURATION) {
        return historicalDataCache;
    }

    const basePath = process.env.NEXT_PUBLIC_BASE_PATH || '';
    const t0 = Date.now();
    addLog('info', 'Historical', '→ Loading historical-ward-data.json...');

    try {
        const response = await fetch(`${basePath}/historical-ward-data.json`);
        if (!response.ok) {
            addLog('warn', 'Historical', `✗ File not found (${response.status}) — run: npm run build:historical`);
            return new Map();
        }

        const json = await response.json();

        const result = new Map<RaceType, HistoricalRaceData[]>();
        for (const [raceType, races] of Object.entries(json.data as Record<string, any[]>)) {
            result.set(raceType as RaceType, (races as any[]).map(r => ({
                ...r,
                // Deserialize plain object back to Map
                wardResults: new Map<string, WardResult>(Object.entries(r.wardResults)),
            })));
        }

        historicalDataCache = result;
        cacheTimestamp = Date.now();

        const totalRaces = Array.from(result.values()).reduce((s, arr) => s + arr.length, 0);
        const totalWards = Array.from(result.values()).flatMap(a => a).reduce((s, r) => s + r.wardResults.size, 0);
        addLog('success', 'Historical', `✓ ${totalRaces} races, ${totalWards} ward entries (generated: ${json.generatedAt?.slice(0, 10)})`, undefined, Date.now() - t0);
        return result;
    } catch (error) {
        addLog('error', 'Historical', `✗ Error loading: ${String(error)}`);
        return new Map();
    }
}

export interface HistoricalRaceSummary {
    electionId: string;
    electionName: string;
    electionDate: string;
    raceId: string;
    raceName: string;
    raceType: RaceType;
    wardCount: number;
}

/**
 * Returns a flat list of all available historical races, sorted newest-first.
 * Used to populate the comparison race picker in the TURNOUT overlay.
 */
export async function getAllAvailableRaces(): Promise<HistoricalRaceSummary[]> {
    const data = await fetchHistoricalData();
    const results: HistoricalRaceSummary[] = [];
    for (const races of data.values()) {
        for (const race of races) {
            results.push({
                electionId: race.electionId,
                electionName: race.electionName,
                electionDate: race.electionDate,
                raceId: race.raceId,
                raceName: race.raceName,
                raceType: race.raceType,
                wardCount: race.wardResults.size,
            });
        }
    }
    results.sort((a, b) => new Date(b.electionDate).getTime() - new Date(a.electionDate).getTime());
    return results;
}

/**
 * Like getAllAvailableRaces(), but filters to races that share at least one
 * normalized ward key with the current live race. This prevents the comparison
 * picker from showing geographically irrelevant races (e.g. a county-wide
 * Presidential race as a comparison for a single aldermanic district race).
 * Falls back to all races when no ward keys are provided.
 */
export async function getAvailableRacesWithOverlap(
    currentWardKeys: string[]
): Promise<HistoricalRaceSummary[]> {
    const data = await fetchHistoricalData();
    if (currentWardKeys.length === 0) return getAllAvailableRaces();

    const keySet = new Set(currentWardKeys);
    const results: HistoricalRaceSummary[] = [];

    for (const races of data.values()) {
        for (const race of races) {
            const hasOverlap = Array.from(race.wardResults.keys()).some(k => keySet.has(k));
            if (hasOverlap) {
                results.push({
                    electionId: race.electionId,
                    electionName: race.electionName,
                    electionDate: race.electionDate,
                    raceId: race.raceId,
                    raceName: race.raceName,
                    raceType: race.raceType,
                    wardCount: race.wardResults.size,
                });
            }
        }
    }

    results.sort((a, b) => new Date(b.electionDate).getTime() - new Date(a.electionDate).getTime());
    return results;
}

/**
 * Get the most recent historical race of a given type.
 * Races are already sorted newest-first in the JSON.
 */
export async function getMostRecentHistoricalRace(raceType: RaceType): Promise<HistoricalRaceData | null> {
    const data = await fetchHistoricalData();
    const races = data.get(raceType);
    return races && races.length > 0 ? races[0] : null;
}

/**
 * Get historical comparison data for a specific ward.
 */
export async function getHistoricalComparison(
    wardKey: string,
    currentRaceType: RaceType
): Promise<{
    historical: WardResult | null;
    historicalRaceName: string | null;
    historicalElectionDate: string | null;
} | null> {
    const mostRecent = await getMostRecentHistoricalRace(currentRaceType);
    if (!mostRecent) return null;

    return {
        historical: mostRecent.wardResults.get(wardKey) || null,
        historicalRaceName: mostRecent.raceName,
        historicalElectionDate: mostRecent.electionDate,
    };
}
